version: '3'
services:
  mysql_database:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Fortaleza
    networks:
      system-network:
        ipv4_address: 150.10.0.4
  redis_server:
    container_name: redis
    image: redis
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      system-network:
        ipv4_address: 150.10.0.7
  api-system:
    image: node
    container_name: api-node
    environment:
      - mysql_host=mysql_database
      - mysql_port=3306
      - mysql_user=root
      - mysql_password=root
      - mysql_database=cars
      - mysql_connectionLimit=10
      - redis_host=redis_server
      - redis_port=6379
      - redis_default_expire=86400
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    command: bash -c "cd /home/node/app && npm run dev"
    networks:
      system-network:
        ipv4_address: 150.10.0.11
    depends_on:
      - redis_server
      - mysql_database
networks:
  system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 150.10.0.0/24